name: flutter_ble_peripheral_example
description: Demonstrates how to use the flutter_ble_peripheral plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  permission_handler: ^8.3.0
  flutter:
    sdk: flutter

  flutter_ble_peripheral:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true