on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      
name: Build Flutter
env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
jobs:
  build:
    name: Build Android & iOS on MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.3.0
        with:
          channel: 'dev'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
        working-directory: ./example
      - run: flutter test
        working-directory: ./example
      - run: flutter build apk --debug --split-per-abi
        working-directory: ./example
      - run: cd ./example/ios && pod install
      - run: flutter test
        working-directory: ./example
      - run: flutter build ios --release --no-codesign
        working-directory: ./example