on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      
name: Build Flutter
jobs:
  build-android:
    name: Build Android on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.3.0
        with:
          flutter-version: '1.12.13+hotfix.9'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk

  build-ios:
    name: Build iOS on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.3.0
        with:
          flutter-version: '1.12.13+hotfix.9'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build ios --release --no-codesign